### PR TITLE
Make a timestamp macro with ms and add to uncommon messages

### PR DESCRIPTION
**Pull request by kanoi**
Main change is adding ms accuracy - but also as a macro, so it's easy to use anywhere (and easy to change if required)
Running on linux

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Hmm, if you're gonna change the format anyway, why not just switch to time-since-epoch? The server stuff all uses that to make it machine-readable... Any idea how many poolops do machine-processing of their logs? (I ask because if we switch to seconds or ms since epoch it makes more sense to only call printf once). Otherwise looks good.

**Comment by kanoi** [comment]
Yeah I spend my life looking at screen logs - so it's easy to compare visually when something appears.
Maybe add the sec.usec also before/after the stamp?

**Comment by kanoi** [comment]
Yeah adding this accuracy shows the poor transmission times of the current public relay.
Guess I better just use it in my own git.

**Comment by TheBlueMatt** [comment]
Hmm? I was being lazy since I had a big rewrite I was testing to merge first. Where are you seeing poor transmission times?

**Comment by kanoi** [comment]
You need this accuracy to make any useful analysis of the relay times.

**Comment by TheBlueMatt** [comment]
Wait, so are you saying this showed you some bad relay times or just you got tired of waiting? Anyway, I've been planning on merging, just been busy rewriting the server side code and a new protocol version. Should have that stuff mostly done in a week or two depending on how much I get done while in HK.

**Comment by kanoi** [comment]
No, it shows unexpected results from multiple relays at certain times.
Indeed I've not done a reliable analysis of it yet - though, as I said, this accuracy would be necessary to do that, however:

I guess at this point I need to state the obvious.
Using such a relay is way faster than not using it.

Peer to peer relaying of blocks is slow (by nature) but even slower due to the bitcoin protocol being unable to be upgraded to include trust and thus allow faster transmission of valid hashed blocks that are not fully transaction verified. Full verification takes a **LONG** time. Full verification is required in bitcoind before transferring a block to another node, yet that other node will of course also do that full verification before considering it.
In gmaxwell's words: https://github.com/bitcoin/bitcoin/issues/7049#issuecomment-157569702
> In general our experience suggests that trust settings are black magic that cannot be configured correctly even by experts

The down side of that black magic of trust would be that invalid blocks would be checked by more nodes. However if that trust level check included an **EXCEPTIONALLY** quick check of the hash and that the block indeed hashes a known previous block, then that would greatly reduce the amount of invalid block relaying done by bitcoin, using this black magic, since creating a hashed valid block is not all that easy to do ...

So it would seem that you have indeed produced black magic with your relay.

**Comment by TheBlueMatt** [comment]
I think you might be surprised with how fast block validation is on reasonably nice hardware (ie most servers you'd ever buy or recent hardware you'd buy if you care at all about performance) is (often faster than network latency). The inefficiency of the p2p network seems to come a bunch from the way the networking stack is written (incl the message processing thread and the way relay is done), but mostly from the fact that it is a p2p network... You're never gonna best something that is centralized and smart enough to get better routing.

I'm confused on what you mean by unexpected results, though. I know sometimes relays won't compress well (go look at 21's blocks.....) and end up spending time compressing for no gain, only to lose more packets than some miner's personal relay network and not win the race (there's an issue about exploring non-tcp relays and I'm gonna turn off the p2p access to the relay network soon which should help some).

As for the relay network introducing trust relationships in Bitcoin, I'd hope no one is spv mining on its headers (it probably won't actually get you much if you do - the spv mining wins are largely related to delays getting the data and calling getblocktemplate, not validating the block, so just validating the block and using the blocknotofy stuff to create your own empty block should be just as quick).

**Comment by kanoi** [comment]
I think you might be surprised at just how slow bitcoind full verification is on good hardware ... I doubt you've verified it's performance, if you'd make the statement suggesting it's fast.

I've verified this on fast hardware over many months where I have full logs of the stages of block changes ... and this was the first reason why I added ms accuracy to cgminer and ckpool (in the past) and now the relay also (though I hacked it into my copy of the relay code a while back also)

Here the last 2 blocks:

    Relay time : [2015-11-27 23:45:00.816+00] ...00005b1c ...
    Notify time : 2015-11-27 23:45:01.806+00 ... 00005b1c ...
    Relay time : [2015-11-27 23:45:38.823+00] ...000052d0 ...
    Notify time : 2015-11-27 23:45:39.294+00 ... 000052d0 ...

The first case a 990ms gross processing time, the second case a 471ms gross processing time.
And yes I can find fast ones also - it's not the hardware that's the issue, bitcoind's full block verification takes a lot of CPU power.

Hmm maybe gmaxwell is right about people not understanding trust and considering trust black magic ...
My bitcoind (since it is based on core) does full validation.
The relay network allows fast relaying of blocks without the unnecessary full validation of those blocks multiple extra times ...
... since my node that receives the block does the full validation once rather than it being done **MANY** times during the peer 2 peer bitcoind version of block relaying ... and thus slowing down he bitcoin peer 2 peer block relay dramatically.


> As for the relay network introducing trust relationships in Bitcoin, I'd hope no one is spv mining on its headers

f2pool, who you recently helped get the relay working well for them, SPV mines
The fact that they SPV mine has been **VERY** common knowledge in the bitcoin world for a long time ... and was discussed in the #bitcoin-dev IRC channel when the major v2/v3 fork occurred due to SPV mining ... and they publicly state they do also.

**Comment by TheBlueMatt** [comment]
Yes, excuse me, I was basing my assertion partially on how Bitcoin Core master (ie 0.12) performs. Between using libsecp256k1 for signature verification, the mempool limiting stuff, the better sigcache, the smarter BIP30 handling, etc (see https://github.com/bitcoin/bitcoin/issues/6976 and, eg, https://github.com/bitcoin/bitcoin/pull/7037), block connection (and getblocktemplate) are much faster. Also, adding a massive dbcache and running things on an SSD can make a massive difference.

I'm aware that SPV mining is happeneing (f2pool is not the only major miner who does it), but I have no indication that f2pool is SPV mining on blocks it receives from the relay network. As mentioned in the last comment, I do not think f2pool would see similar gains by SPV mining on relay network headers.

**Comment by jameshilliard** [comment]
> I'm aware that SPV mining is happeneing (f2pool is not the only major miner who does it), but I have no indication that f2pool is SPV mining on blocks it receives from the relay network. As mentioned in the last comment, I do not think f2pool would see similar gains by SPV mining on relay network headers.

f2pool's SPV mining is stratum based so this is correct.

**Comment by kanoi** [comment]
>     I'm aware that SPV mining is happeneing (f2pool is not the only major miner who
>     does it), but I have no indication that f2pool is SPV mining on blocks it receives
>     from the relay network. As mentioned in the last comment, I do not think f2pool
>     would see similar gains by SPV mining on relay network headers.
> f2pool's SPV mining is stratum based so this is correct.

... so that's where you got the idea of poolbench when the 2 of you were working with f2pool ... the way they do their spv is the same
... maybe if any pools want to, they might want to stop f2pool (and antpool and ...) using their nodes to spv mine ...

**Comment by jameshilliard** [comment]
> ... maybe if any pools want to, they might want to stop f2pool (and antpool and ...) using their nodes to spv mine ...

Blocking f2pool from SPV mining off of your pool would really only hurt your own pool since it would slow down their block changes for blocks you mine.

**Comment by kanoi** [comment]
>      ... maybe if any pools want to, they might want to stop f2pool
>      (and antpool and ...) using their nodes to spv mine ...
> Blocking f2pool from SPV mining off of your pool would really only hurt your own pool since it would slow down their block changes for blocks you mine.

Ah the power of a larger misbehaving mining pool over a smaller mining pool.
We should bow down to their power and let them use our nodes for SPV mining ... since ... ? are you saying SPV mining is ok and we should not hinder them?
Yes indeed there may be a negative effect on my node ... of course I should think only of that negative effect and not care at all about SPV mining ... let money and power decide what is best to do ...

Firstly, there's 3 ways to do SPV mining:
1) mining stratum on other pools (which at the moment they are even scummy enough to do dead mining - no actual hardware mining, just connecting to other pools and using their block change information ... wow a pool that big wont even put up any hash rate to another pool they are using to help them SPV mine ...yeah that's the obvious hint how to stop them at the moment)
2) relay - doesn't matter what you guys say, the relay is blatantly obviously faster than the peer 2 peer block relaying of the network ... otherwise there's no point to the relay ... and only a fool would think that coders are unable to do the same simple SPV mining that is done with their dead stratum mining nodes. It may not be used for that at the moment, but anyone with half an ounce of nous would spot the obvious
3) bitcoin daemon - again the obvious for any coder - change in there to do something with the block when it first arrives rather than wait for verification
4) did I say 3? Yeah the obvious 4th is to (slowly) code their own versions of 1, 2 and 3 rather than just hack into current code and get it done quickly.

**Comment by kanoi** [comment]
The macro itself (as is obvious) is just c, not c++
Recent 0.12 of bitcoin master has a c++ version which may 'look' better for this since it's c++

**Comment by TheBlueMatt** [comment]
Though I'm gonna avoid commenting on 1 or 3, the point I was making is less that it is somehow impossible to SPV mine on what you get back from the relay network (obviously that is bogus), but that doing so will likely not net you very much with a reasonable architecture. Since there is little to no time between receiving the block header on the relay connection and receiving the full block, the only advantage to SPV mining on the relay network is (in a properly-architected pool) local block validation latency. WIth a warm sigcache and utxo cache, this is incredibly fast on 0.12, (50 to 200 ms or so) at which point its largely not worth the risk of maybe, once, mining an invalid block because of it.

**Comment by TheBlueMatt** [comment]
I dont care much at all about C vs C++, though I do care about avoiding additional printfs (ala HASH_PRINT and HASH_FORMAT, which have fixed a bunch of bugs on the log-processing stuff :) )

**Comment by kanoi** [comment]
yeah the main point to that was to be able to just stick the macro anywhere it was required without having to rewrite the message printed after it (since the macro's not linefeed terminated)

**Comment by TheBlueMatt** [comment]
Yea, I only mention it in general, it was a big issue since there are multiple block prints near the same time, it shouldn't really ever be an issue for clients or where its used here. Merged (without the change to relayproxy).

**Pull request closed without merging**
